### ISSUE TITLE
Roadmap for noobjs 1.0.0

### ISSUE THREAD

**Issue by invisal** [invisal/noobjs#1]
Algorithms to be implemented for noobjs 1.0.0

- Basic Data Structure
  - [x] Stack
  - [x] Queue
  - [x] Priority Queue using Binary Heap

- Graph
   - [x] Graph Representation
   - [ ] Depth-First Search
   - [ ] Breadth-First search
   - [x] Minimum Spanning Tree using Prim's algorithm

- Machine Learning
   - [x] k-nearest Neighbor Classifier
   - [ ] k-mean Clustering
   - [x] Linear Regression
   - [ ] Naive Bayes Classifier using Gaussian Distribution

- Math
   - [x] BigNumber: Long Addition
   - [x] BigNumber: Long Division
   - [x] BigNumber: Long Multiplication
   - [x] BigNumber: Long Subtraction
   - [x] Matrix: Multiplication using brute force
   - [x] Matrix: Inversion using Gaussian Elimination
   - [x] Matrix: Transpose
   - [x] Prime:  Sieve of Eranthoses
   - [x] Prime: Primality test using brute force approach
   - [ ] Prime: Factorization using Pollard's rho algorithm
